[package]
name = "paig-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-as-inner = "0.6.0"
im = "15.1.0"
pest = "2.7.5"
pest_derive = "2.7.5"
thiserror = "1.0.50"
